/**
 * Canonical error codes returned in RFC 7807 problem+json responses
 * under the `code` field. Clients (Android, admin dashboard) switch on these
 * exact string values — do NOT rename without coordinating with the clients.
 */
export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_OTP: 'AUTH_INVALID_OTP',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_RATE_LIMITED: 'AUTH_OTP_RATE_LIMITED',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_REFRESH_TOKEN_REUSE_DETECTED: 'AUTH_REFRESH_TOKEN_REUSE_DETECTED',
  AUTH_UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',

  // Workers / catalog
  WORKER_NOT_FOUND: 'WORKER_NOT_FOUND',
  WORKER_UNAVAILABLE: 'WORKER_UNAVAILABLE',
  PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND',
  SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',

  // Orders
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  ORDER_RESERVATION_EXPIRED: 'ORDER_RESERVATION_EXPIRED',
  ORDER_RESERVATION_FAILED: 'ORDER_RESERVATION_FAILED',

  // Payments
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_INTENT_NOT_FOUND: 'PAYMENT_INTENT_NOT_FOUND',
  PAYMENT_WEBHOOK_SIGNATURE_INVALID: 'PAYMENT_WEBHOOK_SIGNATURE_INVALID',

  // Promos
  PROMO_NOT_FOUND: 'PROMO_NOT_FOUND',
  PROMO_INACTIVE: 'PROMO_INACTIVE',
  PROMO_EXPIRED: 'PROMO_EXPIRED',
  PROMO_USAGE_LIMIT_REACHED: 'PROMO_USAGE_LIMIT_REACHED',
  PROMO_NOT_APPLICABLE: 'PROMO_NOT_APPLICABLE',

  // Identity verification (Signit.sa)
  VERIFICATION_REQUIRED: 'VERIFICATION_REQUIRED',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  VERIFICATION_EXPIRED: 'VERIFICATION_EXPIRED',
  VERIFICATION_WEBHOOK_SIGNATURE_INVALID: 'VERIFICATION_WEBHOOK_SIGNATURE_INVALID',

  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
